name: Test Infrastructure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install boto3 pytest moto

      - name: Run tests
        run: |
          pytest tests/unit/test_handler.py
